[project]
name = "porotta"
version = "0.1.0"
description = "ThE EdItOr"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "gradio>=6.24.0",
    "opencv-python-headless>=5.0.0.93",
]

[project.scripts]
porotta = "porotta:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
